<a href="https://colab.research.google.com/github/raavimanoj016/Portfolio/blob/main/Finding_nps_of__airbnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Importing Numpy

    

In [2]:
import numpy as np

## NPS (Net Promoter Score)



#### How to calculate NPS score? 

<img src="https://drive.google.com/uc?id=1KPIYlaN68vlL99iApaF5QbeBoyT24-Eu">

We label our responses into 3 categories:
- Detractors: Respondents with a score of 0-6
- Passive: Respondents with a score of 7-8
- Promoters: score of 9-10.

And
```
Net Promoter score = % Promoters - % Detractors.
```



#### Lets first look at the data we have gathered


Dataset: https://drive.google.com/file/d/1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK/view?usp=sharing

<img width = 500 src="https://drive.google.com/uc?id=1arJhLlzbr_Rf7ONxpkzo726mLbTyLb_p">




#### Notice that the file contains the score for likelyhood to recommend survey


**Using NumPy** 
- we will bin our data into promoters/detractors
- calulate the percentage of promoters/detractors 
- calculate NPS



In [3]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 3.91MB/s]


#### Let's load the data we saw earlier. For this we will use `.loadtxt() function`

Documentation: https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html

In [4]:
score = np.loadtxt('survey.txt', dtype ='int')

We provide file name along with the dtype of data we want to load in 

Let's see what the data looks like

In [5]:
score[:5]

array([ 7, 10,  5,  9,  9])

#### Let's check the number of responses

In [6]:
score.shape

(1167,)


#### Let's check the minimum and max value

In [7]:
score.min()

1

In [8]:
score.max()

10

Looks like, there are no records with 0 score.

Now, let's calculate NPS using these response.

**NPS = % Promoters - % Detractors**

Now, in order to calculate NPS, we need to calculate two things:
- % Promoters
- % Detractors

#### Let's get the count of promoter and detractors

Detractors have a score <=6

In [ ]:
detractors = score[score <= 6].shape[0]

In [ ]:
total = score.shape[0]

In [ ]:
percent_detractors = detractors/total*100

In [ ]:
percent_detractors

28.449014567266495

Similarly, Promoters have a score 9-10

In [ ]:
promoters = score[score >= 9].shape[0]

In [ ]:
percent_promoters = promoters/total*100

In [ ]:
percent_promoters

52.185089974293064

#### Calculating NPS

For calculating NPS, we need to 

`% promoters - % detractors `

In [ ]:
nps = percent_promoters - percent_detractors
nps

23.73607540702657

In [ ]:
np.round(nps)

24.0

We will map our scores into 3 categories s.t:

- 0 - 6:  Detractors

- 7 - 8: Passive

- 9 - 10: Prometers

This is called **binning**


In [10]:
arr = np.empty(shape = score.shape, dtype = 'str')

In [ ]:
arr

array(['', '', '', ..., '', '', ''], dtype='<U1')

Notice the following
- All the elements of the array are empty string
- The dtype is being shown as `U1`.

Now, we have got a string array. Let's bin our score values

In [11]:
arr[score <= 6] = 'detractors'

In [ ]:
arr

array(['', '', 'detractors', ..., 'detractors', '', ''], dtype='<U10')

Similarly, we can do it for passive and promoters

In [ ]:
arr[(score >= 7) & (score <= 8)] = 'passive'

In [ ]:
arr[score >= 9] = 'promoters'

In [ ]:
arr

array(['passive', 'promoters', 'detractors', ..., 'detractors',
       'promoters', 'promoters'], dtype='<U10')

In [ ]:
arr[:15]

array(['passive', 'promoters', 'detractors', 'promoters', 'promoters',
       'detractors', 'passive', 'promoters', 'promoters', 'promoters',
       'promoters', 'detractors', 'promoters', 'promoters', 'passive'],
      dtype='<U10')

In [ ]:
detractors_count = arr[arr == 'detractors'].shape[0]

In [ ]:
detractors_count

332

In [ ]:
passive_count = arr[arr == 'passive'].shape[0]
passive_count

226

In [ ]:
promoters_count = arr[arr == 'promoters'].shape[0]
promoters_count

609

The short way:

Use `.unique()` to get unique element 

In [ ]:
np.unique(arr)

array(['detractors', 'passive', 'promoters'], dtype='<U10')

We can pass argument `return_counts = True` for count of each unique element.


In [ ]:
np.unique(arr, return_counts = True)

(array(['detractors', 'passive', 'promoters'], dtype='<U10'),
 array([332, 226, 609]))

In [ ]:
unique, counts = np.unique(arr, return_counts = True)

In [ ]:
unique

array(['detractors', 'passive', 'promoters'], dtype='<U10')

In [ ]:
counts

array([332, 226, 609])

#### % Promoters

In [ ]:
percent_promoters = counts[2]/counts.sum()*100

#### % Detractors

In [ ]:
percent_detractors = counts[0]/counts.sum()*100

#### Calculating NPS

In [ ]:
nps = percent_promoters - percent_detractors
nps

23.73607540702657

In [ ]:
np.round(nps)

24.0

#### (Optional) What is a good NPS score ?

<img src="https://drive.google.com/uc?id=1FYgRM2XmJs4Rv-l8CCUn_aXcyw7GfZlp">

Source: https://chattermill.com/blog/what-is-a-good-nps-score/
